# global pipeline variables applied to all pipelines
# modify only for version upgrades
variables:
  # set semantic version for the current build
  version: '1.0.0'
  # variable to create a unique build number (https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#counter)
  build: $[counter(variables['version'], 1)]
  # identify a pull request build
  isPR: $[eq(variables['Build.Reason'], 'PullRequest')]
  # don't interfere with code coverage publishing.
  disable.coverage.autogenerate: 'true'