# pipeline to 'test' creation and modification of pipelines.

variables:
  - template: templates/azure-pipelines-variables.yml

resources:
  - repo: self

trigger:
  branches:
    # only trigger the build for these defined branches (based on branch naming conventions)
    include:
      - features/*
      - bugs/*
  paths:
    # prevent build trigger if only docs have changed
    exclude:
      - docs
      - readme.md

stages:
  # perform build and unit tests, publish artifacts and test reports
  - stage: build
    displayName: build and test
    jobs:
      - template: ./templates/azure-pipelines-build-template.yml
        parameters:
          name: 'build_soure'
          isReleaseBranch: false