# pipeline to 'test' creation and modification of pipelines.

variables:
  - template: templates/azure-pipelines-variables.yml

resources:
  - repo: self

trigger:
  branches:
    # modify pipeline builds on separate branch so it does not triggered the dev builds
    include:
      - pipeline/*
  paths:
    # prevent build trigger if only docs have changed
    exclude:
      - docs
      - readme.md
pr: none # disable pull request triggers.

stages:
  # perform build and unit tests, publish artifacts and test reports
  - stage: build
    displayName: build and test
    jobs:
      - template: ./templates/azure-pipelines-build-template.yml
        parameters:
          name: 'build_soure'
          isReleaseBranch: false